[2024-03-09 18:35:31,018] torch.distributed.run: [WARNING] 
[2024-03-09 18:35:31,018] torch.distributed.run: [WARNING] *****************************************
[2024-03-09 18:35:31,018] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-03-09 18:35:31,018] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "/sailhome/jphilipp/research_projects/typo/experiments/experiment_2/train_typo.py", line 27, in <module>
    from helpers import *
  File "/sailhome/jphilipp/research_projects/typo/experiments/experiment_2/helpers.py", line 143, in <module>
    @dataclass
NameError: name 'dataclass' is not defined
Traceback (most recent call last):
  File "/sailhome/jphilipp/research_projects/typo/experiments/experiment_2/train_typo.py", line 27, in <module>
    from helpers import *
  File "/sailhome/jphilipp/research_projects/typo/experiments/experiment_2/helpers.py", line 143, in <module>
    @dataclass
NameError: name 'dataclass' is not defined
Traceback (most recent call last):
  File "/sailhome/jphilipp/research_projects/typo/experiments/experiment_2/train_typo.py", line 27, in <module>
    from helpers import *
  File "/sailhome/jphilipp/research_projects/typo/experiments/experiment_2/helpers.py", line 143, in <module>
    @dataclass
NameError: name 'dataclass' is not defined
Traceback (most recent call last):
  File "/sailhome/jphilipp/research_projects/typo/experiments/experiment_2/train_typo.py", line 27, in <module>
    from helpers import *
  File "/sailhome/jphilipp/research_projects/typo/experiments/experiment_2/helpers.py", line 143, in <module>
    @dataclass
NameError: name 'dataclass' is not defined
[2024-03-09 18:35:36,029] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1408267) of binary: /scr/jphilipp/miniconda3/envs/typo/bin/python
Traceback (most recent call last):
  File "/scr/jphilipp/miniconda3/envs/typo/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/scr/jphilipp/miniconda3/envs/typo/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/scr/jphilipp/miniconda3/envs/typo/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/scr/jphilipp/miniconda3/envs/typo/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/scr/jphilipp/miniconda3/envs/typo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/scr/jphilipp/miniconda3/envs/typo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_typo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-09_18:35:36
  host      : cocoflops-hgx-1.stanford.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1408268)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-03-09_18:35:36
  host      : cocoflops-hgx-1.stanford.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1408269)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-03-09_18:35:36
  host      : cocoflops-hgx-1.stanford.edu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1408270)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-09_18:35:36
  host      : cocoflops-hgx-1.stanford.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1408267)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
